[book]
authors = ["Sabrina Andersen (NukingDragons), Patrick Jenkins (Drone), Thomas Wells (mesumine), Jonathan Brown (numonce), Tyler McCann (tylerdotrar)"]
language = "en"
multilingual = false
src = "src"
title = "Hacknum-Opus"

[build]
build-dir = "public"
